stages:
  - generator
  - check
  - build
  - test
  - config
  - deploy
  - pm # permanently maintenance

generate:env:
  stage: generator
  variables:
    GIT_STRATEGY: none
  script:
    - echo "APP_VERSION=$(date +%Y.%m.%M.%s)" >> build.env
  artifacts:
    reports:
      dotenv: build.env

include:
  # - local: ".gitlab/cicd/config/config-server.yml"
  - local: ".gitlab/cicd/check/check-prettier.yml"
  # - local: ".gitlab/cicd/check/check-sonarqube.yml"
  # - local: ".gitlab/cicd/check/check-spell.yml"
  - local: ".gitlab/cicd/build/build-production.yml"
    rules:
      - if: '$CI_COMMIT_TAG =~ /v[0-9]*\.[0-9]*\.[0-9]*/'

  - local: ".gitlab/cicd/deploy/deploy-production.yml"
    rules:
      - if: '$CI_COMMIT_TAG =~ /v[0-9]*\.[0-9]*\.[0-9]*/'

  - local: ".gitlab/cicd/build/build-test.yml"
    rules:
      - if: '$CI_COMMIT_BRANCH == "master"'

  - local: ".gitlab/cicd/deploy/deploy-test.yml"
    rules:
      - if: '$CI_COMMIT_BRANCH == "master"'

  # - local: ".gitlab/cicd/build/build-local.yml"

  # - local: ".gitlab/cicd/test/test-local.yml"

  # - local: ".gitlab/cicd/pm/pm-update-server.yml"
