export * as Loader from "./loader";
export * as Home from "./home";
export * as Login from "./login";
export * as User from "./user";
export * as Driver from "./driver";
export * as Admin from "./admin";
export * as Category from "./category";
export * as Auth from "./auth";
export * as Banner from "./banner";
export * as SocialMedia from "./social-media";
export * from "./rules";
export * from "./contact-us";
export * from "./about-us";
export * from "./sms";
export * as Logout from "./logout";
export * as page404 from "./404";
export * as Ticket from "./ticket";
export * from "./id-pay";
export * as Trip from "./trip";
