version: "3"

services:
  webapp:
    container_name: webapp
    command: "npm start"
    # build: .
    image: node:17.3.1
    working_dir: /app
    ports:
      - 3000:3000
    environment:
      UID_WWW_DATA: "502"
      GID_WWW_DATA: "20"
      VIRTUAL_HOST: "localhost"
    volumes:
      - ./../../..:/app
